/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   ArcIcons.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.

import {svg} from 'lit-element';
import { SVGTemplateResult } from 'lit-html';

export {
  iconWrapper,
  accountCircle,
  addCircleOutline,
  add,
  arcIcon,
  arcIconArrows,
  archive,
  arrowBack,
  arrowDropDown,
  arrowDropUp,
  assignment,
  bugReport,
  build,
  cached,
  chevronLeft,
  chevronRight,
  cancel,
  clear,
  clearAll,
  close,
  cloudDownload,
  code,
  collectionsBookmark,
  insertComment,
  contentCopy,
  deleteIcon,
  desktopWindows,
  done,
  driveColor,
  drive,
  edit,
  error,
  expandLess,
  expandMore,
  exportVariant,
  fileDownload,
  filterList,
  folderShared,
  help,
  helpOutline,
  history,
  home,
  importExport,
  info,
  infoOutline,
  insertChart,
  insertDriveFile,
  keyboardArrowDown,
  keyboardArrowUp,
  keyboardArrowRight,
  list,
  markdown,
  menu,
  message,
  modeEdit,
  moreVert,
  newReleases,
  notificationsActive,
  openInNew,
  ramlR,
  rateReview,
  refresh,
  removeCircleOutline,
  pinDrawer,
  spellcheck,
  sentimentVeryDissatisfied,
  sentimentNeutral,
  save,
  saveAlt,
  search,
  send,
  settings,
  shield ,
  shortText,
  star,
  starBorder,
  viewColumn,
  viewList,
  visibility,
  visibilityOff,
  warning,
  wrapText,
  zoomIn
};


/**
 * Wraps icon into an SVG container.
 *
 * @returns Complete SVG icon definition
 */
declare function iconWrapper(tpl: SVGTemplateResult|null): SVGTemplateResult|null;

declare const accountCircle: SVGTemplateResult;
declare const addCircleOutline: SVGTemplateResult;
declare const add: SVGTemplateResult;
declare const arcIcon: SVGTemplateResult;
declare const arcIconArrows: SVGTemplateResult;
declare const archive: SVGTemplateResult;
declare const arrowBack: SVGTemplateResult;
declare const arrowDropDown: SVGTemplateResult;
declare const arrowDropUp: SVGTemplateResult;
declare const assignment: SVGTemplateResult;
declare const bugReport: SVGTemplateResult;
declare const build: SVGTemplateResult;
declare const cached: SVGTemplateResult;
declare const chevronLeft: SVGTemplateResult;
declare const chevronRight: SVGTemplateResult;
declare const cancel: SVGTemplateResult;
declare const clear: SVGTemplateResult;
declare const clearAll: SVGTemplateResult;
declare const close: SVGTemplateResult;
declare const cloudDownload: SVGTemplateResult;
declare const code: SVGTemplateResult;
declare const collectionsBookmark: SVGTemplateResult;
declare const insertComment: SVGTemplateResult;
declare const contentCopy: SVGTemplateResult;
declare const deleteIcon: SVGTemplateResult;
declare const desktopWindows: SVGTemplateResult;
declare const done: SVGTemplateResult;
declare const driveColor: SVGTemplateResult;
declare const drive: SVGTemplateResult;
declare const edit: SVGTemplateResult;
declare const error: SVGTemplateResult;
declare const expandLess: SVGTemplateResult;
declare const expandMore: SVGTemplateResult;
declare const exportVariant: SVGTemplateResult;
declare const fileDownload: SVGTemplateResult;
declare const filterList: SVGTemplateResult;
declare const folderShared: SVGTemplateResult;
declare const help: SVGTemplateResult;
declare const helpOutline: SVGTemplateResult;
declare const history: SVGTemplateResult;
declare const home: SVGTemplateResult;
declare const importExport: SVGTemplateResult;
declare const info: SVGTemplateResult;
declare const infoOutline: SVGTemplateResult;
declare const insertChart: SVGTemplateResult;
declare const insertDriveFile: SVGTemplateResult;
declare const keyboardArrowDown: SVGTemplateResult;
declare const keyboardArrowUp: SVGTemplateResult;
declare const keyboardArrowRight: SVGTemplateResult;
declare const list: SVGTemplateResult;
declare const markdown: SVGTemplateResult;
declare const menu: SVGTemplateResult;
declare const message: SVGTemplateResult;
declare const modeEdit: SVGTemplateResult;
declare const moreVert: SVGTemplateResult;
declare const newReleases: SVGTemplateResult;
declare const notificationsActive: SVGTemplateResult;
declare const openInNew: SVGTemplateResult;
declare const ramlR: SVGTemplateResult;
declare const rateReview: SVGTemplateResult;
declare const refresh: SVGTemplateResult;
declare const removeCircleOutline: SVGTemplateResult;
declare const pinDrawer: SVGTemplateResult;
declare const spellcheck: SVGTemplateResult;
declare const sentimentVeryDissatisfied: SVGTemplateResult;
declare const sentimentNeutral: SVGTemplateResult;
declare const save: SVGTemplateResult;
declare const saveAlt: SVGTemplateResult;
declare const search: SVGTemplateResult;
declare const send: SVGTemplateResult;
declare const settings: SVGTemplateResult;
declare const shield : SVGTemplateResult;
declare const shortText: SVGTemplateResult;
declare const star: SVGTemplateResult;
declare const starBorder: SVGTemplateResult;
declare const viewColumn: SVGTemplateResult;
declare const viewList: SVGTemplateResult;
declare const visibility: SVGTemplateResult;
declare const visibilityOff: SVGTemplateResult;
declare const warning: SVGTemplateResult;
declare const wrapText: SVGTemplateResult;
declare const zoomIn: SVGTemplateResult;
